kind: Service
apiVersion: v1
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
  name: hellobrave
spec:
  selector:
    app: hellobrave
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hellobrave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellobrave
  template:
    metadata:
      labels:
        app: hellobrave
    spec:
      imagePullSecrets:
      - name: dockerhub
      containers:
      - name: hellobrave
        image: "__CONTAINER_REGISTRY__/hellobrave:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
