kind: Secret
apiVersion: v1
metadata:
  name: myregistrykey
data:
  .dockerconfigjson: L3Jvb3QvLmRvY2tlci9jb25maWcuanNvbgo=
type: kubernetes.io/dockerconfigjson
---
kind: Service
apiVersion: v1
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
  name: ${APP_NAME}
spec:
  selector:
    app: ${APP_LABEL}
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${APP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_LABEL}
  template:
    metadata:
      labels:
        app: ${APP_LABEL}
    spec:
      imagePullSecrets:
      - name: dockerhub
      containers:
      - name: ${APP_NAME}
        image: "${CONTAINER_REGISTRY}/hellobrave:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
